// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "projectileUP":return img`
. . . . . . 1 b b . . . . . . . 
. . . . . b b . . b b . . . . . 
. . . . b . . . . . 1 b . . . . 
. . . b . . . . . . . . b 1 . . 
. 1 b . 1 . . . . . . 1 . b . . 
. b . 1 . . . . . . . . 1 . b . 
b 1 . . . . . . . . . . . . . b 
b . . . . . . . . . . . . . 1 b 
b . . . . . . . . . . . . . . b 
1 . . . . . . . . . . . . . . 1 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image5":
            case "projectileLEFT":return img`
. . . . . . b b b 1 . . . . . . 
. . . . . b 1 . . . . . . . . . 
. . . . b . . . . . . . . . . . 
. . . b . . . . . . . . . . . . 
. . b . 1 . . . . . . . . . . . 
. b . 1 . . . . . . . . . . . . 
. b . . . . . . . . . . . . . . 
b . . . . . . . . . . . . . . . 
b 1 . . . . . . . . . . . . . . 
. b . . . . . . . . . . . . . . 
. b . . . . . . . . . . . . . . 
. . b . 1 . . . . . . . . . . . 
. . . b . 1 . . . . . . . . . . 
. . . . b . . . . . . . . . . . 
. . . . . b . . . . . . . . . . 
. . . . . 1 b b b 1 . . . . . . 
`;
            case "image6":
            case "projectileRIGHT":return img`
. . . . . . 1 b b b . . . . . . 
. . . . . . . . . . b . . . . . 
. . . . . . . . . . . b . . . . 
. . . . . . . . . . 1 . b 1 . . 
. . . . . . . . . . . 1 . b . . 
. . . . . . . . . . . . . . b . 
. . . . . . . . . . . . . . b . 
. . . . . . . . . . . . . . 1 b 
. . . . . . . . . . . . . . . b 
. . . . . . . . . . . . . . b . 
. . . . . . . . . . . . . . b . 
. . . . . . . . . . . 1 . b . . 
. . . . . . . . . . 1 . b . . . 
. . . . . . . . . . . b . . . . 
. . . . . . . . . 1 b . . . . . 
. . . . . . 1 b b b . . . . . . 
`;
            case "image2":
            case "sword effect":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
1 . . . . . . . . . . . . . . 1 
b . . . . . . . . . . . . . . b 
b . . . . . . . . . . . . . . b 
b . . . . . . . . . . . . . . b 
. b . . . . . . . . . . . . b . 
. . b . 1 . . . . . . 1 . b 1 . 
. . . b . 1 . . . . 1 . b . . . 
. . . . b . . . . . . b . . . . 
. . . . . b b . 1 b b . . . . . 
. . . . . . . b b . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image1":
            case "Lucistnik":return img`
. . . . . . . . . . . . 
. . . f f f f f f . . . 
. f f f e e e e e f . . 
f f f e e e e e e e f . 
f f f f e e e e e e e f 
f f f f f e e e 4 e e f 
f f f f e e e 4 4 e e f 
f f f f 4 4 4 4 4 e f f 
f f 4 e 4 f f 4 4 e f . 
f f 4 d 4 d d d d f . . 
. f f f 4 d d b b f . . 
. 4 d d e 4 4 4 e f . . 
. e d d e 1 1 1 1 f . . 
. f e e f 6 6 6 6 f f . 
. f f f f f f f f f f . 
. . f f . . . f f f . . 
`;
            case "image3":
            case "rock":return img`
. . b d b . . . . . b b b b . . 
. c b d d b . . . b b d d d b . 
. b c c b . . . b c d d d d b . 
. . . . . . b b c c b d b b b . 
. . . . . b d d b c c b b b c . 
. . b b b c d d b b c c c c . . 
. b d d d b c b b c . . . . . . 
c b d d d d c c c c . b b b . . 
c c b b b b c c c . b d d d b . 
. c c c b b . . b c b b d d b b 
. b b . . . . . b c c b b b b . 
b d d b b . . . . . c c c b . . 
b b d d b c . . b b b b b b b . 
. b c c c b . b d d d b b c b . 
. . . . . . b d d d b c c b . . 
. . . . . . b b b c c c b . . . 
`;
            case "image7":
            case "spoustec":return img`
........................
...........88...........
..........8668..........
..........8668..........
.........f6666f.........
........f866668f........
.......8666666668.......
......866866668668......
......f8866666688f......
.....f886686686688f.....
....f88ff88688fff88f....
....ffff88fff88f8fff....
.....f8f8ff8ff8f88f.....
....f88fff88fffff8f.....
....f8ffff8fffffffff....
....fff88ffffff88fff....
....f868ffff8fff868f....
...f666ff8f86f8ff668....
..f6666866866f6686668...
.f66686666666866668668..
.ff8866666666666666866f.
.f8866686686866686668ff.
..ff668868f88f66888688f.
..f8ff88fff88ff8f88ff88f
.f88ff8ff8f8f88fff8fffff
f88ff8ff88ffff88ffff8f..
ffff88f88ffffff8f8ff88f.
.f8ffffffffffffff88ff8f.
.ff6fffff8ff8ff6ff8f6ff.
.f668f6686ff66f6668866ff
f668666866f666868666866f
fff666f6688666666f666ff.
..ffff86f866688668ffff..
.....f8ff66f888ff8f.....
......fff8fff88ffff.....
.........ffeeff.........
.........feeeef.........
.........feeeef.........
........feeefeef........
........fefeffef........
`;
            case "image8":
            case "swordUP":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image9":
            case "Spoustec":return img`
6 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "sword attack up":
            case "anim1":return [img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..ccc.....
.feeffeeeefeeef.ccdc.....
..feeeeeeeeeef.ccddc.....
...feeeeeeeef.cdddc......
..e4ffffffff4ecdcc.......
..4df222222fd4ccc........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff.ccc.......
.ffef2feef2feffcdc.......
.feeffeeeefeeefddc.......
..feeeeeeeeeefcdc........
...feeeeeeeefcddc........
..e4ffffffff4edc.........
..4df222222fd4cc.........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.cc..........
...feeeffeeefcdc.........
..fffff22fffffdc.........
..ffe2e22e2effdcc........
..fe2f2ff2f2efddc........
..fff22ee22fffdc.........
.ffef2feef2feffc.........
.feeffeeeefeeef..........
..feeeeeeeeeefc..........
...feeeeeeeefc...........
..e4ffffffff4e...........
..4df222222fd4...........
..44f444444f44...........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..ccc.....
.feeffeeeefeeef.ccdc.....
..feeeeeeeeeef.ccddc.....
...feeeeeeeef.cdddc......
..e4ffffffff4ecdcc.......
..4df222222fd4ccc........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..........
.feeffeeeefeeef..........
..feeeeeeeeeef...........
...feeeeeeeef............
..e4ffffffff4e...........
..4df222222fd4...........
..44f444444f44...........
.....ffffff..............
.....ff..ff..............
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
