// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Lucistnik":return img`
. . . . . . . . . . . . 
. . . f f f f f f . . . 
. f f f e e e e e f . . 
f f f e e e e e e e f . 
f f f f e e e e e e e f 
f f f f f e e e 4 e e f 
f f f f e e e 4 4 e e f 
f f f f 4 4 4 4 4 e f f 
f f 4 e 4 f f 4 4 e f . 
f f 4 d 4 d d d d f . . 
. f f f 4 d d b b f . . 
. 4 d d e 4 4 4 e f . . 
. e d d e 1 1 1 1 f . . 
. f e e f 6 6 6 6 f f . 
. f f f f f f f f f f . 
. . f f . . . f f f . . 
`;
            case "image2":
            case "sword effect":return img`
. . . . . . . . . . . . 1 b . . 
. . . . . . . . . . . . 1 b . . 
. . . . . . . . . . . . . b . . 
. . . . . . . . . . . . 1 b . . 
. . . . . . . . . . . . . b . . 
. . . . . . . . . . . . 1 b . . 
. . . . . . . . . . . . b . . . 
. . . . . . . . . . 1 . b . . . 
. . . . . . . . . 1 . b . . . . 
. . . . . . . . . . b . . . . . 
. . . . . . . . 1 b . . . . . . 
. . . . . . . . b . . . . . . . 
. . 1 . 1 . b b . . . . . . . . 
b b b b b b 1 . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "rock":return img`
. . b d b . . . . . b b b b . . 
. c b d d b . . . b b d d d b . 
. b c c b . . . b c d d d d b . 
. . . . . . b b c c b d b b b . 
. . . . . b d d b c c b b b c . 
. . b b b c d d b b c c c c . . 
. b d d d b c b b c . . . . . . 
c b d d d d c c c c . b b b . . 
c c b b b b c c c . b d d d b . 
. c c c b b . . b c b b d d b b 
. b b . . . . . b c c b b b b . 
b d d b b . . . . . c c c b . . 
b b d d b c . . b b b b b b b . 
. b c c c b . b d d d b b c b . 
. . . . . . b d d d b c c b . . 
. . . . . . b b b c c c b . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "sword attack up":
            case "anim1":return [img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..........
.feeffeeeefeeef..........
..feeeeeeeeeef...........
...feeeeeeeef............
..e4ffffffff4e...........
..4df222222fd4...........
..44f444444f44...........
.....ffffff..............
.....ff..ff..............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..ccc.....
.feeffeeeefeeef.ccdc.....
..feeeeeeeeeef.ccddc.....
...feeeeeeeef.cdddc......
..e4ffffffff4ecdcc.......
..4df222222fd4ccc........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff.ccc.......
.ffef2feef2feffcdc.......
.feeffeeeefeeefddc.......
..feeeeeeeeeefcdc........
...feeeeeeeefcddc........
..e4ffffffff4edc.........
..4df222222fd4cc.........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.cc..........
...feeeffeeefcdc.........
..fffff22fffffdc.........
..ffe2e22e2effdcc........
..fe2f2ff2f2efddc........
..fff22ee22fffdc.........
.ffef2feef2feffc.........
.feeffeeeefeeef..........
..feeeeeeeeeefc..........
...feeeeeeeefc...........
..e4ffffffff4e...........
..4df222222fd4...........
..44f444444f44...........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff.ccc.......
.ffef2feef2feffcdc.......
.feeffeeeefeeefddc.......
..feeeeeeeeeefcdc........
...feeeeeeeefcddc........
..e4ffffffff4edc.........
..4df222222fd4cc.........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..ccc.....
.feeffeeeefeeef.ccdc.....
..feeeeeeeeeef.ccddc.....
...feeeeeeeef.cdddc......
..e4ffffffff4ecdcc.......
..4df222222fd4ccc........
..44f444444f44c..........
....fffffffff............
....fff....ff............
`, img`
......ffff...............
....ffeeeeff.............
...feeeffeeef............
..fffff22fffff...........
..ffe2e22e2eff...........
..fe2f2ff2f2ef...........
..fff22ee22fff...........
.ffef2feef2feff..........
.feeffeeeefeeef..........
..feeeeeeeeeef...........
...feeeeeeeef............
..e4ffffffff4e...........
..4df222222fd4...........
..44f444444f44...........
.....ffffff..............
.....ff..ff..............
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
